# Generated by Django 3.1.6 on 2021-02-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_terminal',
            name='T2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
