# Generated by Django 3.1.6 on 2021-02-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_terminal', '0002_data_terminal_t2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_terminal',
            name='SW',
            field=models.CharField(max_length=2),
        ),
    ]
