# Generated by Django 3.1.6 on 2021-02-05 07:04

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_terminal', '0003_auto_20210204_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_terminal',
            name='TS',
            field=unixtimestampfield.fields.UnixTimeStampField(),
        ),
    ]
