# Generated by Django 3.1.6 on 2021-02-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_terminal', '0004_auto_20210205_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_terminal',
            name='TS',
            field=models.IntegerField(),
        ),
    ]
