# Generated by Django 3.1.6 on 2021-02-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_terminal', '0005_auto_20210205_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_terminal',
            old_name='T1',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='data_terminal',
            name='T2',
        ),
        migrations.RemoveField(
            model_name='data_terminal',
            name='T3',
        ),
        migrations.RemoveField(
            model_name='data_terminal',
            name='T4',
        ),
        migrations.RemoveField(
            model_name='data_terminal',
            name='T5',
        ),
    ]
