# Generated by Django 3.1.6 on 2021-02-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_terminal', '0008_auto_20210207_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert_report',
        ),
    ]
